### ISSUE TITLE
why a new plugin?

### ISSUE THREAD

**Issue by mathuaerknedam** [josephschmitt/Snipe#13]
This isn't really an issue, so hopefully it will be easy to resolve. :)

I'm curious why you created a new plugin rather than using one of the existing plugins with the same basic functionality? (I tried a few before settling on TabSearch.)

**Comment by josephschmitt** [comment]
No one else's implementation really worked the way I wanted it to. Plus, I love building things, and building Snipe taught me a lot, having a lot of that knowledge transfer directly over to the work I do at Vimeo (specifically Music Store).
