### ISSUE TITLE
Window resize 

### ISSUE THREAD

**Issue by ghost** [josephschmitt/Snipe#5]
When using the keyboard shortcut or the omnibar the it resize the browser.

**Comment by josephschmitt** [comment]
What Operating System and version are you on? What version of Chrome? Do you have any extensions enabled that would keep popups from being created?

**Comment by ghost** [comment]
Windows 7 ultimate x32, Chrome beta 10.0.648.119 i disable all the extensions and keep doing the same.

**Comment by josephschmitt** [comment]
Thanks, I'll try to reproduce the issue.

**Comment by ghost** [comment]
Thanks to you for the extensions. This is my first bug report and i'm glad to help :)

**Comment by josephschmitt** [comment]
I'm still unable to reproduce the issue. I tried it in Chrome 10.0.648 and got this when I hit the shortcut key. http://cl.ly/4rvq (I'll be fixing the scrollbars issue in the next update).

From what I'm understanding, you're saying the extension is resizing your main Chrome window? It's not making a small popup window that includes the Snipe window? Can you attach a screenshot?

**Comment by ghost** [comment]
i was trying to say that it resize my main chrome window the extension works well but when i use the keyboard shortcut or the omnibar to change tabs when i change the tab it resize the chrome main window.

sorry for my bad english

**Comment by ghost** [comment]
here are the screenshots maximized http://twitpic.com/442xuo/full then when i use the extension http://twitpic.com/442y1a/full

**Comment by josephschmitt** [comment]
I have a potential fix. Would you mind uninstalling the version you have installed from the Web Store and then installing this version here http://cl.ly/4ruW

Let me know if it fixes the issue where it resizes the window. Thanks.

**Comment by ghost** [comment]
Wao that was fast now it works like a charm and the keyboard shortcut windows looks better thanks :D

**Comment by josephschmitt** [comment]
Not a problem, thanks to you! Your screenshot helped me reproduce the problem on my own computer. I didn't understand that what people meant was that it was removing people out of maximized mode. I thought it was actually resizing the window. Thanks a lot for your help!

**Comment by josephschmitt** [comment]
I've uploaded the new version to the store so you might want to uninstall the developer version I just gave you and grab the latest from the store (make sure it's version 0.3.5.3). That way you still get auto-updates.

Cheers.

**Comment by ghost** [comment]
I install the latest version 3.5.3 from the store but it does the same i think you uploaded the wrong version. 

never mind now it works

**Comment by josephschmitt** [comment]
Make sure you refresh all of your tabs before trying again (or just restart your browser). The extension doesn't update on any open pages.

**Comment by ghost** [comment]
Yes now it work .

Cheers.

**Comment by josephschmitt** [comment]
Great! Thanks again.

**Comment by ghost** [comment]
Thanks to you for your awesome extension :D

**Comment by ghost** [comment]
After the new update today the resize problem is back.

**Comment by josephschmitt** [comment]
Shoot, sorry about that. Mind uninstalling the Store version and installing this one to see if it's fixed? http://cl.ly/50Uv

**Comment by ghost** [comment]
Now it works again :)

**Comment by josephschmitt** [comment]
Awesome. I've pushed out an updated version to the Store. Thanks for the catch!
