### ISSUE TITLE
Sometime Control-Alt-Space Doesn't Work

### ISSUE THREAD

**Issue by cwoodall** [josephschmitt/Snipe#6]
I have been having an issue where Control-Alt-Space will scroll down my page instead of bringing Snipe up. 

Also, you should be able to assign your Snipe Hot Key yourself

**Comment by josephschmitt** [comment]
Have you refreshed all of your open tabs after installing the extension (either manually, or by simply re-starting your browser)? Also, what OS version are you running, and what browser version?

**Comment by cwoodall** [comment]
I re-started Chrome a few times. I am running OS X and Chrome 11.0.672.2 dev.

I tested it again and it seems to be working fine now, but if I start having issues again I will chime in.

**Comment by josephschmitt** [comment]
Great to hear. Unfortunately refreshing your tabs after installation is a necessary evil since Chrome doesn't natively support keyboard shortcuts. I have to add window event listeners via a content script and that doesn't get run until a page is refreshed.
