### ISSUE TITLE
Feature Request: Vim-style shortcuts

### ISSUE THREAD

**Issue by rbugajewski** [josephschmitt/Snipe#7]
It would be great to have an alternate way of navigating through Snipe in a Vim-like way:

Ctrl-J -> Down Arrow
Ctrl-K -> Up Arrow
Ctrl-L -> Return

LaunchBar does this for example. I’ve mapped my Tab-Key to Ctrl and I’m totally used to navigate without the arrows.

**Comment by josephschmitt** [comment]
Interesting, didn't know about these. I recently added support for Ctrl+N and Ctrl+P. Can you think of any other shortcuts for up and down? I'd rather add them all at once.

**Comment by rbugajewski** [comment]
Not really. I only know the Vim way, and the arrow keys way.

Tab and Some-Modifier+Tab would be probably also nice for a couple of people (like the application or window switcher in Mac OS X).

**Comment by josephschmitt** [comment]
Ok, I'll look into rolling this into the next release. Thanks for the suggestion.

**Comment by rbugajewski** [comment]
Thanks for this neat extension. It saves my time… every day.

**Comment by josephschmitt** [comment]
version 0.4.5, Added support for using Ctrl + K and Ctrl + J to navigate the tab search results, and Ctrl + L to select. Closed by c9f06226efeeeaa1b4db0ef3e89d545226aefa92.

**Comment by josephschmitt** [comment]
Should auto-update if you have the Safari or Chrome webstore versions installed. Thanks again for the suggestion. Cheers.
