### ISSUE TITLE
UI always shows both search and config sides at once

### ISSUE THREAD

**Issue by ghostwords** [josephschmitt/Snipe#9]
Displayed fine at first, broke at some point later (after a browser upgrade?). Using Chrome 11 on a Mac.

![](http://i.imgur.com/qyXw8.png)

**Comment by josephschmitt** [comment]
Hmmm, beta versions of Chrome 11 had support for -webkit-backface-visibility so I had a check on there to use it if your version of Chrome was 11 or greater. It seems that the release version removed it. I'll update it to wait for Chrome 12+.

Thanks.

**Comment by ghostwords** [comment]
Great extension, by the way!

**Comment by josephschmitt** [comment]
Looks like Chrome 12 supports 3D transforms finally, so this should be fixed if you update.
